from pathlib import Path
from typing import Dict, Any

class MarkdownRenderer:
    def __init__(self, output_path: str):
        self.output_path = Path(output_path)
        # Ensure the deepaudit/docs directory exists
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def render(self, registry: Dict[str, Any]):
        """Generates the final Markdown file from the AST registry."""
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write("# 💎 Sapphire Collective: DeepAudit API Codex\n")
            f.write("> *Auto-generated by DeepAudit v0.3.0 Engine*\n\n")
            f.write("---\n\n")

            for file_path, data in registry.items():
                if not data["classes"] and not data["functions"]:
                    continue 

                # Clean the file path so it just shows 'deepaudit/engine/parser.py' etc.
                clean_path = Path(file_path).relative_to(Path.cwd() / "src")
                f.write(f"## 📦 Module: `{clean_path}`\n\n")

                for cls in data["classes"]:
                    f.write(f"### Class: `{cls['name']}`\n")
                    f.write(f"{cls['doc']}\n\n")

                for func in data["functions"]:
                    params = func['params'] if func['params'] else "()"
                    f.write(f"#### `def {func['name']}{params}`\n")
                    f.write(f"{func['doc']}\n\n")