from pathlib import Path
from typing import Dict, Any

class MarkdownRenderer:
    def __init__(self, output_path: str = "docs/API_CODEX.md"):
        self.output_path = Path(output_path)
        # Ensure the docs directory exists
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def render(self, registry: Dict[str, Any]):
        """Generates the final Markdown file from the AST registry."""
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write("# Sapphire Collective: DeepAudit API Codex\n")
            f.write("> *Auto-generated by DeepAudit*\n\n")
            f.write("---\n\n")

            for file_path, data in registry.items():
                if not data["classes"] and not data["functions"]:
                    continue # Skip empty files

                f.write(f"## Module: `{file_path}`\n\n")

                # Render Classes
                for cls in data["classes"]:
                    f.write(f"### Class: `{cls['name']}`\n")
                    f.write(f"{cls['doc']}\n\n")

                # Render Functions
                for func in data["functions"]:
                    params = func['params'] if func['params'] else "()"
                    ret = f" -> {func['return']}" if func['return'] else ""
                    
                    f.write(f"#### `def {func['name']}{params}{ret}`\n")
                    f.write(f"{func['doc']}\n\n")
